spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fileupdown?serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
    suffix: .html
    encoding: UTF-8
    prefix: classpath:/templates/
  resources:
    static-locations: classpath:/templates/,classpath:/static/,classpath:/public/,classpath:/resources/
mybatis:
  mapper-locations: classpath:com/charon/fileupdown/mapper/*.xml
  type-aliases-package: com/fileupdown/charon/file/entity
logging:
  level:
    root: info
    com.fileupdown.charon.file.dao: debug
